setting up my Azure client

In [2]:
%pip install setuptools==81.0.0

Requirement already satisfied: setuptools==81.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (81.0.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: /anaconda/envs/azureml_py310_sdkv2/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
from azure.ai.ml.entities import AzureBlobDatastore
from azure.ai.ml.entities import Data
from azure.ai.ml import MLClient
from azure.identity import DefaultAzureCredential
from azure.ai.ml.constants import AssetTypes
from azure.ai.ml.entities import AccountKeyConfiguration
import mltable
from mltable import MLTableHeaders, MLTableFileEncoding

ml_client = MLClient.from_config(credential=DefaultAzureCredential())

Found the config file in: /config.json

get the datastore

In [7]:
# get the datastore
datastore = ml_client.datastores.get_default()

# build the path to the raw file
datastore_path = f"azureml://datastores/{datastore.name}/paths/Online Retail.xlsx"

# register it as a data asset
retail_data = Data(
    path=datastore_path,
    name="online-retail-raw",
    version="1",
    type=AssetTypes.URI_FILE,
    description="Raw UCI Online Retail transaction dataset for customer segmentation"
)

registered_data = ml_client.data.create_or_update(retail_data)

In [8]:
# confirm set up
print("Name:", registered_data.name)
print("Version:", registered_data.version)
print("Type:", registered_data.type)
print("Path:", registered_data.path)

Name: online-retail-raw
Version: 1
Type: uri_file
Path: azureml://subscriptions/9d0e4acf-2675-4581-90be-c8f45f73d333/resourcegroups/clustering-project/workspaces/clustering-workspace/datastores/clusterdatastore/paths/Online Retail.xlsx

conversion of excel to parquet

In [9]:
# retrieving the raw data

raw_data = ml_client.data.get(
    name="online-retail-raw",
    version="1"
)

print(raw_data.path)

azureml://subscriptions/9d0e4acf-2675-4581-90be-c8f45f73d333/resourcegroups/clustering-project/workspaces/clustering-workspace/datastores/clusterdatastore/paths/Online Retail.xlsx

package for easy access to azure ml storage URIs by Python/Panda

In [10]:
%pip install -U azureml-fsspec openpyxl pyarrow

Requirement already satisfied: azureml-fsspec in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (1.3.1)
Collecting azureml-fsspec
  Downloading azureml_fsspec-1.4.0-py3-none-any.whl.metadata (3.8 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: pyarrow in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (24.0.0)
Collecting pyarrow
  Downloading pyarrow-25.0.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting azureml-dataprep<5.6.0a,>=5.5.0 (from azureml-fsspec)
  Downloading azureml_dataprep-5.5.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: fsspec<=2023.10.0,>=2021.6.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-fsspec) (2023.10.0)
Requirement already satisfied: pytz in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-fsspec) (2026.2)
Collecting azureml-dataprep-native<44.0.0,>=43.0.0 (from azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec)
  Downloading azureml_dataprep_native-43.0.0-cp310-cp310-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting azureml-dataprep-rslex~=2.26.0dev0 (from azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec)
  Downloading azureml_dataprep_rslex-2.26.0-cp310-cp310-manylinux1_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: cloudpickle<3.0.0,>=1.1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (2.2.1)
Collecting azure-identity<=1.17.0,>=1.16.0 (from azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec)
  Downloading azure_identity-1.17.0-py3-none-any.whl.metadata (79 kB)
Requirement already satisfied: jsonschema in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (4.26.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (6.0.3)
Requirement already satisfied: pip>=25.3 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (26.1.2)
Requirement already satisfied: azure-core>=1.23.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (1.41.0)
Requirement already satisfied: cryptography>=2.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (46.0.7)
Requirement already satisfied: msal>=1.24.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (1.37.0)
Requirement already satisfied: msal-extensions>=0.3.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (1.3.1)
Requirement already satisfied: typing-extensions>=4.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (4.15.0)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: requests>=2.21.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azure-core>=1.23.0->azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (2.34.2)
Requirement already satisfied: cffi>=2.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from cryptography>=2.5->azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (2.0.0)
Requirement already satisfied: pycparser in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from cffi>=2.0.0->cryptography>=2.5->azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (3.0)
Requirement already satisfied: PyJWT<3,>=1.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from PyJWT[crypto]<3,>=1.0.0->msal>=1.24.0->azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (2.13.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests>=2.21.0->azure-core>=1.23.0->azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests>=2.21.0->azure-core>=1.23.0->azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests>=2.21.0->azure-core>=1.23.0->azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests>=2.21.0->azure-core>=1.23.0->azure-identity<=1.17.0,>=1.16.0->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (2026.5.20)
Requirement already satisfied: attrs>=22.2.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from jsonschema->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from jsonschema->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from jsonschema->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from jsonschema->azureml-dataprep<5.6.0a,>=5.5.0->azureml-fsspec) (0.30.0)
Downloading azureml_fsspec-1.4.0-py3-none-any.whl (18 kB)
Downloading azureml_dataprep-5.5.0-py3-none-any.whl (253 kB)
Downloading azure_identity-1.17.0-py3-none-any.whl (173 kB)
Downloading azureml_dataprep_native-43.0.0-cp310-cp310-manylinux1_x86_64.whl (167 kB)
Downloading azureml_dataprep_rslex-2.26.0-cp310-cp310-manylinux1_x86_64.whl (26.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 67.5 MB/s  0:00:00m eta 0:00:01
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading pyarrow-25.0.1-cp310-cp310-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 94.1 MB/s  0:00:006m0:00:0100:01
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: azureml-dataprep-rslex, pyarrow, et-xmlfile, azureml-dataprep-native, openpyxl, azure-identity, azureml-dataprep, azureml-fsspec
  Attempting uninstall: azureml-dataprep-rslex
    Found existing installation: azureml-dataprep-rslex 2.22.5
    Uninstalling azureml-dataprep-rslex-2.22.5:
      Successfully uninstalled azureml-dataprep-rslex-2.22.5
  Attempting uninstall: pyarrow━━━━━━━━━━━━━━━━━ 0/8 [azureml-dataprep-rslex]
    Found existing installation: pyarrow 24.0.0m 0/8 [azureml-dataprep-rslex]
    Uninstalling pyarrow-24.0.0:━━━━━━━━━━━━ 0/8 [azureml-dataprep-rslex]
      Successfully uninstalled pyarrow-24.0.0[0m 0/8 [azureml-dataprep-rslex]
  Attempting uninstall: azureml-dataprep-native━━━━━━━━━━━━━━━━━━━ 1/8 [pyarrow]
    Found existing installation: azureml-dataprep-native 41.0.0[0m 1/8 [pyarrow]
    Uninstalling azureml-dataprep-native-41.0.0:━━━━━━━━━━━━━━ 1/8 [pyarrow]
      Successfully uninstalled azureml-dataprep-native-41.0.0━ 1/8 [pyarrow]
  Attempting uninstall: azure-identity━━━━━━━━━━━━━━━━━━━ 4/8 [openpyxl]
    Found existing installation: azure-identity 1.25.3━━━━━━━━ 4/8 [openpyxl]
    Uninstalling azure-identity-1.25.3:[90m━━━━━━━━━━━━━━━━━━━ 4/8 [openpyxl]
      Successfully uninstalled azure-identity-1.25.3━━━━━━━━━━ 4/8 [openpyxl]
  Attempting uninstall: azureml-dataprep90m━━━━━━━━━━━━━━━━━━━ 4/8 [openpyxl]
    Found existing installation: azureml-dataprep 5.1.6━━━━━━━ 4/8 [openpyxl]
    Uninstalling azureml-dataprep-5.1.6:0m╺━━━━━━━━━ 6/8 [azureml-dataprep]
      Successfully uninstalled azureml-dataprep-5.1.6━━━━━━━━━ 6/8 [azureml-dataprep]
  Attempting uninstall: azureml-fsspec╺━━━━━━━━━ 6/8 [azureml-dataprep]
    Found existing installation: azureml-fsspec 1.3.1━━━━━━━━━ 6/8 [azureml-dataprep]
    Uninstalling azureml-fsspec-1.3.1:╺━━━━━━━━━ 6/8 [azureml-dataprep]
      Successfully uninstalled azureml-fsspec-1.3.1m╺━━━━ 7/8 [azureml-fsspec]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [azureml-fsspec]zureml-fsspec]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
azure-monitor-opentelemetry-exporter 1.0.0b53 requires opentelemetry-api==1.40, but you have opentelemetry-api 1.42.1 which is incompatible.
azureml-mlflow 1.62.0.post3 requires azure-storage-blob<=12.27.1,>=12.5.0, but you have azure-storage-blob 12.30.0 which is incompatible.
azureml-mlflow 1.62.0.post3 requires pytz<=2025.2, but you have pytz 2026.2 which is incompatible.
mlflow 3.13.0 requires pyarrow<25,>=4.0.0, but you have pyarrow 25.0.1 which is incompatible.
mltable 1.6.3 requires azureml-dataprep[parquet]<5.5.0a,>=5.1.0a, but you have azureml-dataprep 5.5.0 which is incompatible.
Successfully installed azure-identity-1.17.0 azureml-dataprep-5.5.0 azureml-dataprep-native-43.0.0 azureml-dataprep-rslex-2.26.0 azureml-fsspec-1.4.0 et-xmlfile-2.0.0 openpyxl-3.1.5 pyarrow-25.0.1

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: /anaconda/envs/azureml_py310_sdkv2/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [13]:
#read the registered excel asset

import pandas as pd

df = pd.read_excel(
    raw_data.path,
    engine="openpyxl"
)

Overriding of current MeterProvider is not allowed
Overriding of current TracerProvider is not allowed
Overriding of current LoggerProvider is not allowed
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Overriding of current MeterProvider is not allowed
Overriding of current TracerProvider is not allowed
Overriding of current LoggerProvider is not allowed
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented

In [14]:
df.shape

(541909, 8)

In [22]:
# conversion for parquet
text_columns = [
    "InvoiceNo",
    "StockCode",
    "Description",
    "Country"
]

for column in text_columns:
    df[column] = df[column].astype("string")

In [23]:
df.dtypes

InvoiceNo              string
StockCode              string
Description            string
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                string
dtype: object

In [24]:
# converting to parquet locally
parquet_path = "../data/processed/online_retail.parquet"

df.to_parquet(
    parquet_path,
    engine="pyarrow",
    index=False
)

In [25]:
# verifying the parquet before loading
df_parquet = pd.read_parquet(parquet_path)

print(df_parquet.shape)
df_parquet.head()

(541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [26]:
# confirming if my data structure is still retained
print("Excel shape:", df.shape)
print("Parquet shape:", df_parquet.shape)

Excel shape: (541909, 8)
Parquet shape: (541909, 8)

In [27]:
# final schema check
print(df_parquet.dtypes)

InvoiceNo              string
StockCode              string
Description            string
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                string
dtype: object

uploading the local parquet to datastore

In [6]:
parquet_asset = Data(
    name="online-retail-parquet",
    version="2",
    type=AssetTypes.URI_FILE,
    path="../data/processed/online_retail.parquet"
)

In [7]:
# register as a data asset

registered_parquet = ml_client.data.create_or_update(parquet_asset)

In [8]:
# confirming everything set up prope
print("Name:", registered_parquet.name)
print("Version:", registered_parquet.version)
print("Type:", registered_parquet.type)
print("Path:", registered_parquet.path)

Name: online-retail-parquet
Version: 2
Type: uri_file
Path: azureml://subscriptions/9d0e4acf-2675-4581-90be-c8f45f73d333/resourcegroups/clustering-project/workspaces/clustering-workspace/datastores/workspaceblobstore/paths/LocalUpload/fa3d1d5709e7c559fc2f24c7bc3d851da344356801fd417a88501eb84a703592/online_retail.parquet

In [9]:
# getting path
parquet_asset = ml_client.data.get(
    name="online-retail-parquet",
    version="2"
)

print(parquet_asset.path)

azureml://subscriptions/9d0e4acf-2675-4581-90be-c8f45f73d333/resourcegroups/clustering-project/workspaces/clustering-workspace/datastores/workspaceblobstore/paths/LocalUpload/fa3d1d5709e7c559fc2f24c7bc3d851da344356801fd417a88501eb84a703592/online_retail.parquet

register the data asset as mltable

In [10]:
# creating an mltable object in memory
parquet_uri = registered_parquet.path

tbl = mltable.from_parquet_files(
    paths=[{
        "file":parquet_uri
    }]
)

In [11]:
# confirm structure
test_df = tbl.to_pandas_dataframe()

print(test_df.shape)

test_df.head()

Overriding of current MeterProvider is not allowed
Overriding of current TracerProvider is not allowed
Overriding of current LoggerProvider is not allowed
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Overriding of current MeterProvider is not allowed
Overriding of current TracerProvider is not allowed
Overriding of current LoggerProvider is not allowed
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented

(541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [12]:
# a folder for the mltable definition
import os 

mltable_folder = "../data/mltable/online-retail"

os.makedirs(
    mltable_folder,
    exist_ok=True
)

# save the mltable definition
tbl.save(mltable_folder)

paths:
- file: azureml://subscriptions/9d0e4acf-2675-4581-90be-c8f45f73d333/resourcegroups/clustering-project/workspaces/clustering-workspace/datastores/workspaceblobstore/paths/LocalUpload/fa3d1d5709e7c559fc2f24c7bc3d851da344356801fd417a88501eb84a703592/online_retail.parquet
transformations:
- read_parquet:
    include_path_column: false
    path_column: Path
type: mltable

In [13]:
# registering the mltable as azure asset
mltable_asset = Data(
    name="online-retail-mltable",
    path=mltable_folder,
    version="1",
    type=AssetTypes.MLTABLE,
    description="MLTable for the UCI Online Retail customer segmentation dataset"
)  

registered_mltable = ml_client.data.create_or_update(
    mltable_asset
)

In [16]:
# verifying setup
print("Name:", registered_mltable.name)
print("Version:", registered_mltable.version)
print("Type:", registered_mltable.type)
print("Path:", registered_mltable.path)

Name: online-retail-mltable
Version: 1
Type: mltable
Path: azureml://subscriptions/9d0e4acf-2675-4581-90be-c8f45f73d333/resourcegroups/clustering-project/workspaces/clustering-workspace/datastores/workspaceblobstore/paths/LocalUpload/b342c082372b11e39f0569465f71c3e153a7f63f11582709b2362518245ca18b/online-retail/